### ISSUE TITLE
DB Data should be stored in Persistent volumes

### ISSUE THREAD

**Issue by lgrateau** [ODMDev/odm-docker-kubernetes#4]
The DB Server container instance store the data in their data in their local file system.
If we restart the container the data are lost.
The goal of this issue is to investigate how to map the data container to a Persistent Kubernetes volumes.

Once we know what we have to do we need to modify the different topology (minikube , bluemix and helm chart yml file ) to add this configuration

**Comment by yiquanzhou** [comment]
Useful resources:

- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_kubernetes/get_started_provisioning_storage_in_kubernetes
- https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes
- https://kubernetes.io/docs/concepts/storage/volumes/#nfs

**Comment by lgrateau** [comment]
Finish testing on ICP. Use shared folder with a hostpath PVC.
