### ISSUE TITLE
How to configure Kubernetes liveness and readiness probe

### ISSUE THREAD

**Issue by dhpalan** [ODMDev/odm-docker-kubernetes#63]
I wanted to configure Kubernetes Liveness, Readiness probes for a ODM cluster topology setup.

Are there suitable HTTP endpoints that can be used for probes on all four docker containers?
1. ODM Decision Server runtime
2. ODM Decision Server console
3. ODM Decision Center
4. ODM Decision Runner

**Comment by lgrateau** [comment]
@dhpalan  yes you can take a look in the helm deployment descriptor

**Comment by dhpalan** [comment]
@lgrateau I could not find any configuration for the probes for docker images of Decision Server.
Could you please help me with the information?

> I found out that probes can be sent to Decision Center to path /decisioncenter/healthCheck.
> https://github.com/IBM/charts/blob/30f86b003b21eaa88505b564d4f98e967c90a011/stable/ibm-odm-dev/templates/deployment.yaml#L129-L157

This is helpful when i am running single container for all ODM services.
But we run 4 separate container for each service.
