### ISSUE TITLE
Helm does not support Postgres over SSL

### ISSUE THREAD

**Issue by lwblackledge** [ODMDev/odm-docker-kubernetes#66]
Hello,

I have been attempting to set this up on Azure Kubernetes Service using Azure PostreSQL as storage. However, my company mandates SSL communication to databases, and I do not see a way to specify that option on the helm chart.

Is PostgreSQL over SSL supported?

**Comment by lgrateau** [comment]
Hi @lwblackledge  sorry for the late response. Yes it's supported out of the box since the 8.10.4.0

**Comment by lgrateau** [comment]
for the previou
