### ISSUE TITLE
ODM on EKS: truststore may not be created in JKS format by default

### ISSUE THREAD

**Issue by alainrobert** [ODMDev/odm-docker-kubernetes#90]
on EKS In the command to create the trust store we should add the argument "-storetype JKS". 
If may happen that the truststore is created in PKCS12 format if using the default type. 

https://github.com/ODMDev/odm-docker-kubernetes/blob/96980c2f593fdc95dcf338b8ea03d13b3edad2dc/eks/README.md?plain=1#L273

**Comment by mmouly** [comment]
Hello @alainrobert , in the rewritten version, we removed the command to manage certificate in JKS format as the certificate is exposed by the EKS loadbalancer. 
https://github.com/ODMDev/odm-docker-kubernetes/tree/master/platform/eks#b-upload-the-certificate-to-aws-iam-service
So, there is no need to manage it at the ODM container level.

**Comment by mmouly** [comment]
so, I close it if it's ok for you ... as I know that you never close ticket ;-)
